#Need define ROOT!!!
BOOT=boot.bin
BOOT_LOAD_SEG=0x7c0
BOOT_START_FUN=_start
KERNEL_ENTRY_ADDRESS=0x100000 #1MB + 1KB
KERNEL_ENTRY_FUN=_start

ISO=os.iso

AS=as
CC=gcc
MKISO=mkisofs
LD=ld
RM=rm -rf
QEMU=qemu-system-x86_64
BOCHS=bochs
TOBINARY=objcopy -O binary

CFLAGS=-I $(ROOT)/include -c -fno-builtin -std=c99
ASFLAGS=-I $(ROOT)/include 
MKISOFLAGS=-R -v -no-emul-boot -boot-load-seg $(BOOT_LOAD_SEG) -b $(BOOT)
LDFLAGS_BIN=--oformat binary -e $(BOOT_START_FUN) -Ttext 0x0
LDFLAGS_ELF=-s
QEMUFLAGS=-cdrom $(ISO) -boot d
BOCHSFLAGS=
