ROOT=..
include ../Makefile.config
TARGET=$(ROOT)/bin/kernel
first:cachedir $(TARGET)

clean:
	$(RM) .obj

cachedir:
	if [ ! -d .obj ]; then \
	mkdir .obj; \
	fi
$(TARGET):$(OBJS) $(ROOT)/ldscripts/kernel.lds
	$(LD) $(LDFLAGS_ELF) -T$(ROOT)/ldscripts/kernel.lds -o $(KERNEL_ELF) $(OBJS)
	$(TOBINARY) $(KERNEL_ELF) $(TARGET)
